name: Deploy Gestion Vuelos React

on:
  push:
    branches:
      - main


jobs:

  build-and-deploy:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm


      - name: Crear env
        run: |
          printf "%s" "${{ secrets.REACT_ENV }}" > .env.production


      - name: Instalar dependencias
        run: npm ci


      - name: Build React
        run: npm run build


      - name: Subir dist al VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          source: "dist/*"
          target: "/tmp/react_build"


      - name: Publicar en Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}

          script: |

            rm -rf /var/www/gestion_vuelos_aereopuerto_cotopaxi_react/*

            cp -r /tmp/react_build/dist/* /var/www/gestion_vuelos_aereopuerto_cotopaxi_react/

            chown -R www-data:www-data /var/www/gestion_vuelos_aereopuerto_cotopaxi_react

            nginx -t

            systemctl reload nginx